name: Flutter Build - Android

on:
  workflow_dispatch:  # 手动触发构建

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Create l10n output directory
        run: mkdir -p lib/l10n/generated

      - name: Generate localizations
        run: flutter gen-l10n

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
